baseURL = "https://marco.zyxplay.com/"
languageCode = "en-us"
title = "Marco Fernandes. Developer. Of many things."
theme = "ananke"
publishDir = "docs"
[params]
  logo = "/images/marco-2.png"
  custom_css = ["css/custom.css"]